name: Keep Latest Tag

on:
  push:
    branches:
      - main

jobs:
  keep-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: keep tag
        run: |
          if ! git tag --delete latest 2>/dev/null; then
            echo "Latest tag not found"
          fi
          git tag latest
          git push --tags
